#!/usr/bin/env escript
%% -*- mode: erlang -*-

%% This file is part of Mad, and released under the MIT license.
%% See LICENSE for more information.

main(_) ->
    App = "mad",
    EmuArgs = "-noshell -noinput",
    escript:create(App, [shebang, {comment, ""}, {emu_args, EmuArgs},
                         {archive, files(), []}]),
    ok = file:change_mode(App, 8#764).

files() ->
    [{filename:basename(F), read_file(F)}
     || F <- filelib:wildcard(filename:join("ebin", "*.beam")) ++
            filelib:wildcard(filename:join(["deps", "*", "ebin", "*.beam"]))].

read_file(File) ->
    {ok, Bin} = file:read_file(filename:absname(File)),
    Bin.
