#!/usr/bin/env escript
%% -*- mode: erlang -*-
%% The MIT License

%% Copyright (c) 2013-2014 Sina Samavati <sina.samv@gmail.com>

%% Permission is hereby granted, free of charge, to any person obtaining a copy
%% of this software and associated documentation files (the "Software"), to deal
%% in the Software without restriction, including without limitation the rights
%% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
%% copies of the Software, and to permit persons to whom the Software is
%% furnished to do so, subject to the following conditions:

%% The above copyright notice and this permission notice shall be included in
%% all copies or substantial portions of the Software.

%% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
%% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
%% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
%% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
%% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
%% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
%% THE SOFTWARE.

main(_) ->
    code:add_path("ebin"),
    ok = application:load(mad),
    {ok, Vsn} = application:get_key(mad, vsn),
    make:files(filelib:wildcard(filename:join("src", "*.erl")),
               [debug_info,
                {outdir, "ebin"},
                {d, 'VSN_NUMBER', Vsn},
                {d, 'TIMESTAMP', timestamp()},
                {d, 'GIT_REVISION', revision()},
                {d, 'OTP_RELEASE', erlang:system_info(otp_release)}]),
    escriptize().

escriptize() ->
    App = "mad",
    EmuArgs = "-noshell -noinput",
    escript:create(App, [shebang, {comment, ""}, {emu_args, EmuArgs},
                         {archive, files(), []}]),
    ok = file:change_mode(App, 8#764).

files() ->
    [{filename:basename(F), read_file(F)}
     || F <- filelib:wildcard(filename:join("ebin", "*.beam")) ++
            filelib:wildcard(filename:join(["deps", "*", "ebin", "*.beam"]))].

read_file(File) ->
    {ok, Bin} = file:read_file(filename:absname(File)),
    Bin.

timestamp() ->
    {Mega, Sec, _} = erlang:now(),
    Mega * 1000000 + Sec.

revision() ->
    os:cmd("git rev-parse --short HEAD") -- "\n".
